set nocompatible              
filetype off                  

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
" Plugin 'ycm-core/YouCompleteMe'
Plugin 'scrooloose/nerdtree'
" Plugin 'xuhdev/vim-latex-live-preview'
" Plugin 'lervag/vimtex'

call vundle#end()           
filetype plugin indent on

autocmd vimenter * NERDTree

let g:livepreview_previewer = 'Skim'
let g:livepreview_engine = 'pdflatex'
let g:livepreview_cursorhold_recompule = 0

colorscheme gruvbox

syntax on
set number
set cursorline
set showmatch
set tabstop=4
set shiftwidth=4
set expandtab

autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | exe 'cd '.argv()[0] | endif
map <C-n> :NERDTreeToggle<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
