
# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH=/usr/local/texlive/2019/bin/x86_64-linux:$PATH
export PATH=/usr/local/texlive/2019/bin/x86_64-linux/latexmk:$PATH

# Expand MANPATH
export MANPATH=/usr/local/texlive/2019/texmf-dist/doc/man:$MANPATH

# Expand INFOPATH
export INFOPATH=/usr/local/texlive/2019/texmf-dist/doc/info:$INFOPATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="ben-eastwood"

plugins=(
    git
    z    
    sudo
)

source $ZSH/oh-my-zsh.sh


export LANG=en_US.UTF-8

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='mvim'
fi

export TERM=xterm-256color

alias ranger='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'
alias zshconfig="vim ~/.zshrc"
alias zshsrc="source ~/.zshrc"
alias l="ls -lsp --group-directories-first"
alias la="ls -lspA --group-directories-first"
alias weather="curl wttr.in"
alias c="clear"
