# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/home/mormod/.oh-my-zsh"

ZSH_THEME="eastwood"

plugins=(
git
z
sudo
)

source $ZSH/oh-my-zsh.sh

# store zcomp files in tmp
compinit -d ~/.cache/zsh/zcompdump-$ZSH_VERSION


# aliases
alias untargz="tar xvzf"
alias testsound="aplay /usr/share/sounds/alsa/Front_Center.wav"
alias c="clear"
alias cdc="cd; clear"
alias i3conf="vim ~/.config/i3/config"
alias zshconfig="vim ~/.zshrc"
alias zshsrc="source ~/.zshrc"
alias ohmyzsh="vim ~/.oh-my-zsh"
alias ranger='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'
alias x="exit"
alias untar="tar -zxvf"
alias remoodle="sudo /etc/init.d/apache2 restart"

PATH="/home/mormod/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/home/mormod/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/mormod/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/mormod/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/mormod/perl5"; export PERL_MM_OPT;
