
# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="ben-eastwood"

plugins=(
    git
    z    
)

source $ZSH/oh-my-zsh.sh


export LANG=en_US.UTF-8

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='mvim'
fi

# Compilation flags
export ARCHFLAGS="-arch x86_64"

alias zshconfig="vim ~/.zshrc"
alias zshsrc="source ~/.zshrc"
alias l="ls -lsp"
alias la="ls -lspA"
alias weather="curl wttr.in"

